name: Notched
main: org.kitteh.notched.Notched
authors: ['mbaxter','RROD']
description: Explosive arrows as demonstrated by Notch
version: '${project.version}'
permissions:
  notched.use:
    description: Destroy blocks in an explosion
    default: op
  notched.unlimited:
    description: Not limited to configured max explosion size
    default: op
commands:
  notched:
    description: Kaboom
    usage: |
            /notched
            /notched <size>
            /notched off