name: Notched
main: org.kitteh.notched.Notched
authors: ['RROD','mbaxter']
description: Explosive arrows as demonstrated by Notch
version: 2.0
permissions:
    notched.destroy:
        description: Destroy blocks in an explosion
        default: false